
name: Build, Push and Deploy to AWS

on:
  pull_request:
    paths:
      - 'app/**'
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DHUB_USER }}/api-pazoporras:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DHUB_USER }}/api-pazoporras:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DHUB_USER }}/api-pazoporras:latest
            docker stop api-pazoporras-app || true
            docker rm api-pazoporras-app || true
            docker run -d --name api-pazoporras-app -p 80:8000 ${{ secrets.DHUB_USER }}/api-pazoporras:latest
